# Site Settings
title:               Lagrange
tagline:             a minimalist Jekyll theme
description:
baseurl:            #"/blog"
url:                #"https://260404579.github.io"
github:
  url:               #"https://260404579.github.io/blog"
author:
  name:              "charles"
  email:             "260404579@qq.com"
  twitter:           ""
  instagram:         ""
  github:            "charles427"
  facebook:          ""
  linkedin:          ""
navigation:
- title: About
  url: /about
- title: Writing
  url: /writing
- title: Contact
  url: /contact

paginate:            5
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
